### ISSUE TITLE
pre_test QR code appearance

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#19] opened 2021-02-15 18:02 UTC
Please see the following screen shot of pre_test QR code appearance on the Firefox. It appears to be fine for chrome but on Firefox it is lost the bottom border of the QR code. QR code decoding was fine however, can you resize the pre-test screen to make it fits all information within the display please? 

![image](https://user-images.githubusercontent.com/59022223/107979839-28415280-6fb7-11eb-87d2-685c5a0e1b71.png)

**Comment by FritzHeiden** [comment] 2021-02-16 11:57
I pushed a fix for this. Please check if it resolves your issue

**Comment by yanj-github** [comment] 2021-02-16 12:48
> 
> 
> I pushed a fix for this. Please check if it resolves your issue

Yes I can see the change and it looks fine now.

**Comment by andyburras** [comment] 2021-02-24 16:51
This issue has resurfaced now we have Test Runner executing on a phone device. On a small screen device in landscape the code is severely cropped:
![DSCF0220](https://user-images.githubusercontent.com/28623246/109035271-611cae00-76c0-11eb-8997-1b4d7b92fd7f.JPG)

The QR code needs to be no bigger than those inserted over the video and positioned appropriately:
![DSCF0222](https://user-images.githubusercontent.com/28623246/109035358-7abdf580-76c0-11eb-99ba-61dd88e6bf1b.JPG)

**Comment by louaybassbouss** [comment] 2021-02-25 16:46
@andyburras we didn't focus in our tests on mobile devices. We can set max values for width/height css properties depending of the size of the viewport. We will let you know.

**Comment by FritzHeiden** [comment] 2021-03-10 13:10
I pushed changes to fix the size of the qr code. Please check if this resolves your issue

**Comment by louaybassbouss** [comment] 2021-03-11 13:52
@andyburras feel free to close this issue if you see the issue is fixed on your side

**Comment by louaybassbouss** [comment] 2021-04-13 12:57
> @andyburras feel free to close this issue if you see the issue is fixed on your side
@andyburras can we close this issue?

**Closed** 2021-04-27 08:48 UTC
