### ISSUE TITLE
regular-playback-of-chunked-content-manual

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#26] opened 2021-03-09 11:54 UTC
This test stuck at 59 seconds on the playback and timed out. The test runner didnt finised the test.
Could you kindly have a look see if you have same issue please?

**Comment by louaybassbouss** [comment] 2021-03-09 12:25
@yanj-github  we will check

**Comment by FritzHeiden** [comment] 2021-03-10 12:34
This bug was not exclusive to this test. It occurred due to min buffering time not handled properly by the player. This issue was caused by a min buffer time smaller than the duration of the individual segments. It is now fixed. Please check if this resolves the issue for you

**Comment by louaybassbouss** [comment] 2021-03-11 13:49
@yanj-github feel free to close this issue if it works on your side

**Closed** 2021-03-11 13:57 UTC
