### ISSUE TITLE
Test Runner QR codes on starting up

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-tests#28] opened 2021-03-18 09:13 UTC
When we do some test we found that in some recordings our obsrvation calculated the start up delay is less than 0. 
From further invistigation, detailed bellow, I found it not really clear to me. 

- buffering raised on two events that current times are same but delays are different. 
- buffering and playing current times are same but delays are different.
- most importantly the playing play event comes really late which has direct impact on our claculation. We are calculating start up delay from playing play event. It comes after many frames already shown. We have caculated based on 225 delay as well. 

capture_frame_num=0 session_token=c058a9a6-8704-11eb-8d18-0242ac110002 test_id=775346e6398a1132c475b54148d138bc
status=waiting last_action=initialize Captured on Frame=504
status=buffering last_action=initialize **current_time=20.0 delay=327** Captured on Frame=565
status=buffering last_action=initialize **current_time=20.0 delay=117** Captured on Frame=659
Content ID=L2 Media Time=20083.0 Frame Number=1205 Frame Rate=60.0 Captured on Frame=976
Content ID=L2 Media Time=20100.0 Frame Number=1206 Frame Rate=60.0 Captured on Frame=978
Content ID=L2 Media Time=20117.0 Frame Number=1207 Frame Rate=60.0 Captured on Frame=980
Content ID=L2 Media Time=20133.0 Frame Number=1208 Frame Rate=60.0 Captured on Frame=982
... ...
Content ID=L2 Media Time=20400.0 Frame Number=1224 Frame Rate=60.0 Captured on Frame=1012
Content ID=L2 Media Time=20417.0 Frame Number=1225 Frame Rate=60.0 Captured on Frame=1015
**status=playing last_action=play current_time=20.0 delay=225 Captured on Frame=1015**

**Comment by jpiesing** [comment] 2021-03-18 09:17
The timing of the generation of the events in HTML5 is woefully under-specified and relying on them is really not a good idea. I recommend not doing so.

**Comment by louaybassbouss** [comment] 2021-03-18 09:46
> The timing of the generation of the events in HTML5 is woefully under-specified and relying on them is really not a good idea. I recommend not doing so.

fully agree with Jon you cannot rely on the timing of HTML5 events for the observations. @yanj-github to measure startup time you don't need to wait for `status=playing` but only for first appearance of `action=play` (the time when the Test triggered `video.play()`). Please note also that many players displays the first frame of the video after buffering even without calling `video.play()`.

**Comment by andyburras** [comment] 2021-03-18 10:25
@louaybassbouss Bit confused by that. We only ever see a Status QR Code with an action of "play" that also has a status of "playing". When else should a "play" action appear?

**Comment by louaybassbouss** [comment] 2021-03-18 10:39
> @louaybassbouss Bit confused by that. We only ever see a Status QR Code with an action of "play" that also has a status of "playing". When else should a "play" action appear?
> 
> This is the sequence we see:
> 
> ```
> 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"waiting","a":"initialize"}
> ...
> 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"waiting","a":"initialize"}
> 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"buffering","a":"initialize","d":49}
> ...
> 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"buffering","a":"initialize","d":49}
> 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"playing","a":"play","ct":0.000732,"d":37}
> ...
> ```

Thanks @andyburras this helps us we will check. We will make sure that the first QR Code with action=play is not waiting for any event! if this is the case, then it is a bug and needs to be fixed.

**Comment by yanj-github** [comment] 2021-03-18 10:42
> 
> 
> > @louaybassbouss Bit confused by that. We only ever see a Status QR Code with an action of "play" that also has a status of "playing". When else should a "play" action appear?
> > This is the sequence we see:
> > ```
> > 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"waiting","a":"initialize"}
> > ...
> > 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"waiting","a":"initialize"}
> > 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"buffering","a":"initialize","d":49}
> > ...
> > 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"buffering","a":"initialize","d":49}
> > 2021-03-18 10:33 dpctf_qr_decoder DEBUG    QR code raw data: {"s":"playing","a":"play","ct":0.000732,"d":37}
> > ...
> > ```
> 
> Thanks @andyburras this helps us we will check. We will make sure that the first QR Code with action=play is not waiting for any event! if this is the case, then it is a bug and needs to be fixed.

If I understand it correctly, "s":"playing","a":"play" means current status is playing and previous action is play. I guess we need an event which saying play action is called?

**Comment by andyburras** [comment] 2021-03-18 10:47
I was guessing that the "action" is what TR has asked the device to do, and the "status" is what the device has reported it is doing?
So I think we need an event QR code adding at the point TR requests the play.

**Comment by louaybassbouss** [comment] 2021-03-18 10:48
> If I understand it correctly, "s":"playing","a":"play" means current status is playing and previous action is play. I guess we need an event which saying play action is called?

@yanj-github I confirm that a step is missing. When `video.play()` is triggered but before "playing" event appears, you should see a step `"s":"ready","a":"play"`.  wdyt?

**Comment by andyburras** [comment] 2021-03-18 10:51
Sounds correct to me. Currently we are seeing instances of the first frame appearing before the event QR code, which would be explained by the QR code appearing on receipt of the device's play event.

**Comment by louaybassbouss** [comment] 2021-03-18 10:53
@andyburras  @yanj-github  We will add the new step ASAP and let you know.

**Comment by louaybassbouss** [comment] 2021-03-24 10:36
@yanj-github @andyburras the issue should be fixed now. When play is triggered (the player calls `video.play()`), you should see a QR code with `"s":"ready","a":"play"`. You should see events in this order (the values for `d` and `ct` are just examples):

1. Player is initialising (creating MSE buffer(s), parse MPD, ...)
```json 
{"s":"waiting", "a":"initialize"}
```
2. Player starts buffering
```json 
{"s":"buffering", "a":"initialize", "d":49}
```
3. `video.play()` is triggered after player has enough data to start playback 
```json 
{"s":"ready", "a":"play", "d":35}
```
4. `playing` event is received and after that the currentTime `ct` will be regularly updated  
```json 
{"s":"playing", "a":"play", "ct": 0.000732, "d":37}
```

Can you check and confirm that the issue is fixed on your side. please make sure that you remove the docker cache.

**Comment by jpiesing** [comment] 2021-03-24 13:44
> When play is triggered (the player calls `video.play()`), you should see a QR code with `"s":"ready","a":"play"`.

@louaybassbouss  Does this happen before the call to play() or after the call to play() returns? I know play is mostly async but there is some sync behaviour and there's also the possibility of a non-JavaScript thread running when immediately after play() returns before the next JavaScript is executed.

**Comment by louaybassbouss** [comment] 2021-03-27 09:22
@jpiesing 

> > When play is triggered (the player calls `video.play()`), you should see a QR code with `"s":"ready","a":"play"`.
> 
> @louaybassbouss Does this happen before the call to play() or after the call to play() returns? I know play is mostly async but there is some sync behaviour and there's also the possibility of a non-JavaScript thread running when immediately after play() returns before the next JavaScript is executed.

@jpiesing currently it is implemented after `video.play()` returns. Maybe before `video.play()` is safer if you agree we will change it.

**Comment by jpiesing** [comment] 2021-03-27 10:07
> > > When play is triggered (the player calls `video.play()`), you should see a QR code with `"s":"ready","a":"play"`.
> > 
> > 
> > @louaybassbouss Does this happen before the call to play() or after the call to play() returns? I know play is mostly async but there is some sync behaviour and there's also the possibility of a non-JavaScript thread running when immediately after play() returns before the next JavaScript is executed.
> 
> @jpiesing currently it is implemented after `video.play()` returns. Maybe before `video.play()` is safer if you agree we will change it.

@louaybassbouss Before could be safer depending on the implementation. If you agree then please move it.

**Comment by yanj-github** [comment] 2021-03-29 12:35
Sorry for the delay in response, I have just managed to run one test, it seems fine to me so far.

**Comment by louaybassbouss** [comment] 2021-03-29 14:34
> Sorry for the delay in response, I have just managed to run one test, it seems fine to me so far.

Thanks @yanj-github for confirming. I just provided an update to trigger the QR code before `video.play()`  as agreed with @jpiesing in this [comment](https://github.com/cta-wave/dpctf-tests/issues/28#issuecomment-808705801).  can you confirm that the lastest update is still working for you. We can then close this issue.

**Comment by yanj-github** [comment] 2021-03-30 08:28
@louaybassbouss I think I have already tested with the last commit. Thanks

**Comment by louaybassbouss** [comment] 2021-03-30 08:33
> @louaybassbouss I think I have already tested with the last commit. Thanks

Great thanks @yanj-github then I will close this issue.

**Closed** 2021-03-30 08:34 UTC
Labels: bug
