### ISSUE TITLE
Workflow to Author New Testcases

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/dpctf-tests#90] opened 2022-08-09 17:25 UTC
In GitHub, in the Observation Framework README, there is some information how to support new testcases depending how much they diverge from existing tests.

But, in terms of the overall workflow to author new testcases, it appears the basic steps to create a new testcase, goes something like the following. I was hoping there was more detailed documentation:

Create the HTML5 file, i.e., template.
Create an entry in a 'new' CSV file.
Run generate-tests.py
Optionally, create a new test folder to generate a dedicated test run without having to generate all testcases. Assuming that new CSV file is utilized.
All of this, is hosted and generated locally as opposed to downloading the generated testcases.

Can someone confirm this flow?

Thank you.

**Comment by louaybassbouss** [comment] 2022-08-10 07:41
@javierbarellano4v seems to be duplicate of #89 . Please refer to my comment in #89 .

**Closed** 2022-08-15 13:35 UTC
